<a href="https://colab.research.google.com/github/shuob3344/MSSP6070/blob/main/WeeklyModules/Week05/Participation_Activity_Week_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Question 1.a

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
%run "/content/drive/MyDrive/Gooogle_Connection.py"

Changed directoGit_HUBry to: /content/MSSP6070

# Question 2.b

In [3]:
import pandas as pd

In [4]:
aapl = pd.read_csv('data/aapl.csv')
amzn = pd.read_csv('data/amzn.csv')
fb = pd.read_csv('data/fb.csv')
goog = pd.read_csv('data/goog.csv')
nflx = pd.read_csv('data/nflx.csv')

# Question 2.c

In [5]:
aapl['ticker'] = 'AAPL'
amzn['ticker'] = 'AMZN'
fb['ticker'] = 'FB'
goog['ticker'] = 'GOOG'
nflx['ticker'] = 'NFLX'

# Question 2.d

In [6]:
faang = pd.concat([fb, aapl, amzn, nflx, goog])
faang.head()

         date   open   high    low  close    volume ticker
0  2018-01-02 177.68 181.58 177.55 181.42  18151903     FB
1  2018-01-03 181.88 184.78 181.33 184.67  16886563     FB
2  2018-01-04 184.90 186.21 184.10 184.33  13880896     FB
3  2018-01-05 185.59 186.90 184.93 186.85  13574535     FB
4  2018-01-08 187.20 188.90 186.33 188.28  17994726     FB

# Question 2.e

In [7]:
faang.to_csv('data/faang.csv', index=False)

## Question 2.f

In [9]:
faang = pd.read_csv('data/faang.csv')

In [10]:
faang['date'] = pd.to_datetime(faang['date'])
faang['volume'] = faang['volume'].astype(int)

In [11]:
faang = faang.sort_values(['date', 'ticker'])
faang.head()

           date    open    high     low   close    volume ticker
251  2018-01-02  166.93  169.03  166.04  168.99  25555934   AAPL
502  2018-01-02 1172.00 1190.00 1170.51 1189.01   2694494   AMZN
0    2018-01-02  177.68  181.58  177.55  181.42  18151903     FB
1004 2018-01-02 1048.34 1066.94 1045.23 1065.00   1237564   GOOG
753  2018-01-02  196.10  201.65  195.42  201.07  10966889   NFLX

## Question 2.g

In [12]:
faang.nlargest(7, 'volume')

          date   open   high    low  close     volume ticker
142 2018-07-26 174.89 180.13 173.75 176.26  169803668     FB
53  2018-03-20 167.47 170.20 161.95 168.15  129851768     FB
57  2018-03-26 160.82 161.10 149.02 160.06  126116634     FB
54  2018-03-21 164.80 173.40 163.30 169.39  106598834     FB
433 2018-09-21 219.07 219.65 215.61 215.98   96246748   AAPL
496 2018-12-21 156.19 157.48 148.99 150.09   95744384   AAPL
463 2018-11-02 207.93 212.00 203.84 205.88   91328654   AAPL

## Question 2.h

In [13]:
faang_melted = faang.melt(
    id_vars=['date', 'ticker']
)

faang_melted.head()

        date ticker variable   value
0 2018-01-02   AAPL     open  166.93
1 2018-01-02   AMZN     open 1172.00
2 2018-01-02     FB     open  177.68
3 2018-01-02   GOOG     open 1048.34
4 2018-01-02   NFLX     open  196.10